### PR TITLE
Update extension.js

### PR DESCRIPTION
**Pull request by cocoahooves**
Remove unnecessary GtkClutter import.

### CODE REVIEW

**Comment by LinxGem33** [comment]
@cocoahooves 

really appreciate the PR thank you for taking the time, ill push this upstream once i test the changes on my testing machines.

kind regards

**Comment by cocoahooves** [comment]
You're welcome.

I just updated my primary machine to F26 and had to update a few extensions manually to support 3.24, this was the only outstanding one that needed more than a metadata version bump.

FYI, `journalctl /usr/bin/gnome-shell` is where you can read the JS ERRORS/WARNINGS for extensions.

Thanks for maintaining it.

**Comment by LinxGem33** [comment]
thanks again and ill be sure to use your suggestion in future :smile:

**Comment by CliffS** [comment]
Can confirm it now works for me.  Thanks very much @cocoahooves.

**Pull request merged**
